import Head from "next/head.js";
import { GET } from "../utils/https.js";
import { Context, users } from "@/states/index.js";
import TodoList from "../components/TodoList";
import DefaultLayout from "@/components/layouts/DefaultLayout/DefaultLayout.jsx";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Context.Provider value={users}>
        <DefaultLayout>
          <TodoList />
        </DefaultLayout>
      </Context.Provider>
    </>
  );
}

export async function getServerSideProps(context) {
  const data = await GET("people/1/");

  return {
    props: {
      data: data,
    },
  };
}
