import Head from "next/head.js";
import { Context } from "@/store/index.js";
import TodoList from "../components/TodoList";
import { useReducer } from "react";
import { users } from "@/store/index.js";
import { check } from "@/store/reducers.js";

export default function Home() {
  const [state, dispatch] = useReducer(check, users);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Context.Provider value={{ state, dispatch }}>
        <TodoList />
      </Context.Provider>
    </>
  );
}
